apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodtrack-api
  namespace: moodtrack
  labels:
    app: moodtrack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodtrack-api
  template:
    metadata:
      labels:
        app: moodtrack-api
    spec:
      containers:
        - name: moodtrack-api
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            # ── Auth/JWT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: ALGORITHM

            # ── DB
            - name: SQL_URL
              valueFrom:
                secretKeyRef:
                  name: sql-conn
                  key: url

            # ── Queue (enqueue sentiment)
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: storage-conn
                  key: conn
            - name: SENTIMENT_QUEUE
              valueFrom:
                secretKeyRef:
                  name: storage-conn
                  key: sentiment_queue

            # ── Chiave interna per /internal/*
            - name: JOB_KEY
              valueFrom:
                secretKeyRef:
                  name: job-key
                  key: key

            # ── Azure OpenAI (Assistant API)
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: aoai
                  key: endpoint
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aoai
                  key: api_key
            - name: AZURE_OPENAI_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: aoai
                  key: api_version
            - name: AZURE_OPENAI_ASSISTANT_ID
              valueFrom:
                secretKeyRef:
                  name: aoai
                  key: assistant_id