apiVersion: v1
kind: Service
metadata:
  name: moodtrack-api-svc
  namespace: moodtrack
  annotations:
    service.beta.kubernetes.io/azure-pip-name: moodtrack-api-ip
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-moodtrack-dev
spec:
  type: LoadBalancer
  selector:
    app: moodtrack-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080