testId: moodtrack-api-url
displayName: MoodTrack API URL test
description: End-to-end login + post + list

testModel:
  testType: URL
  testPlan: requests.json             # relativo alla working dir
  engineInstances: 1
  environmentVariables:
    - name: API_BASE
      value: "http://REPLACE_ME"      # lo patchiamo nel workflow

appComponents:
  - resourceId: "/subscriptions/042f1733-7575-499d-b5ef-f51f18ae0f50/resourceGroups/rg-moodtrack-dev/providers/microsoft.insights/components/fa-moodtrack-dev4"

failureCriteria:
  - percentage(error) > 2
  - avg(response_time_ms) > 1500
  - "post-entry: p95(latency) > 700"

autoStop:
  errorPercentage: 10
  timeWindow: 60