version: v0.1
testId: moodtrack-api-url
displayName: MoodTrack API URL test
description: E2E login+post+list
testType: URL
testPlan: requests.json
engineInstances: 1
env:
  - name: API_BASE
    value: "http://placeholder"   # sovrascritto dall'env nel workflow