version: v0.1
testId: moodtrack-api-url
displayName: MoodTrack API URL test
description: End-to-end login + post + list
testType: URL
testPlan: requests.json
engineInstances: 1

# Variabili ambiente sostituite in requests.json
env:
  - name: API_BASE
    value: "http://4.232.242.251"   # oppure endpoint AKS pubblico

# Collega componenti server-side (App Insights) per vedere CPU, richieste, failure nel dashboard ALT
appComponents:
  - resourceId: "/subscriptions/042f1733-7575-499d-b5ef-f51f18ae0f50/resourceGroups/rg-moodtrack-dev/providers/microsoft.insights/components/fa-moodtrack-dev4"

# Criteri di fallimento (SLO/gating)
failureCriteria:
  - percentage(error) > 2             # error rate complessivo
  - avg(response_time_ms) > 700       # media risposta troppo alta
  - "post-entry: p95(latency) > 700"  # regola per singola richiesta

# Arresto automatico se la situazione degenera
autoStop:
  errorPercentage: 10
  timeWindow: 60

# (Opzionale) segreti da Key Vault per non mettere password in chiaro
# secrets:
#   - name: LT_TEST_PASS
#     value: "https://<kv>.vault.azure.net/secrets/lt-pass/<version>"
# referenceIdentities:
#   - kind: KeyVault
#     type: SystemAssigned
