version: v0.1
testId: moodtrack-api-url
displayName: MoodTrack API URL test
description: End-to-end login + post + list

testType: URL
testPlan: requests.json
engineInstances: 1

env:
  - name: API_BASE
    value: "http://REPLACE_ME"

appComponents:
  - resourceId: "/subscriptions/042f1733-7575-499d-b5ef-f51f18ae0f50/resourceGroups/rg-moodtrack-dev/providers/microsoft.insights/components/fa-moodtrack-dev4"

failureCriteria:
  - percentage(error) > 2
  - avg(response_time_ms) > 1500
  - "post-entry: p95(latency) > 700"

autoStop:
  errorPercentage: 10
  timeWindow: 60